name: Deploy to IIS

on:
  push:
    branches:
      - master # Jalankan pipeline saat ada push ke branch `main`

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Sesuaikan dengan versi Node.js di server

      - name: Install dependencies
        run: npm install

      - name: Copy files to IIS server
        run: |
          $iisPath = "D:\Programming\test-iis-node"

          # Hapus semua file dan folder di dalam folder tujuan
          Remove-Item -Path $iisPath\* -Recurse -Force

          # Sekarang salin file baru
          Copy-Item -Path * -Destination $iisPath -Recurse -Force

      - name: Restart IIS
        run: |
          # Gunakan PowerShell untuk merestart IIS setelah deploy
          Invoke-Command -ComputerName "iis-server" -ScriptBlock { iisreset }
